version: '3.9'

services:
  sql:
    container_name: data-sql
    image: mysql:latest
    ports:
      - "3307:3306"
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USERNAME=${DB_USERNAME}
      - TZ=Asia/Seoul
    command:
      - --default-authentication-plugin=mysql_native_password
      - --collation-server=utf8mb4_unicode_ci
      - --character-set-server=utf8mb4
      - --lower_case_table_names=1
    volumes:
      - .sqlVolume:/var/lib/mysql
 
  backend:
    container_name: data-django
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn Cursive.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./backend/:/backend
      - static-volume:/staticfile/
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - sql

  ngnix:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: data-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/con.f/nginx-setup.conf
      - static-volume:/staticfile/

    depends_on:
      - backend

volumes:
  sql:
  backend:
  build_file:
  static-volume: